### ISSUE TITLE
NEP-141 compliance correctness

### ISSUE THREAD

**Issue by joshuajbouw** [aurora-is-near/aurora-engine#191]
This is a tracking issue for [NEP-141] correctness. There are a couple of issues, namely revolving around JSON values. Right now we are Borsh serializing / deserializing but this should be JSON. That and a couple of the returns are returning not as JSON.

There are a few blockers to fixing this which needs to be attacked asap. Firstly, we should be using `serde`'s JSON library `serde-json-core` due to the issue with integer parsing https://github.com/aurora-is-near/aurora-engine/issues/176. Note we can't use `serde_json` because it is not `no_std` compatible. I would imagine that `serde` will be smaller in size than `rjson` so that does need to be measured.

NOTE: The ones that are crossed out below are because of an issue that we can not solve right now without getting off of `no_std` due to `serde`s conflicting with `borsh`.

Tasks:
- [x] ~~Create a branch which replaces `rjson` with `serde` with `serde-json-core`.~~
- [x] ~~Replace `dev-dependency` use of `serde_json` with `serde-json-core`.~~
- [x] ~~Measure changed compilation size. Hopefully, this is less.~~
- [ ] Fix NEP-141 compliance by using JSON with `rjson`, not Borsh.
- [x] fn `storage_deposit` does not return valid JSON. There is a last comma on the which isn't valid in `json`. See: https://github.com/aurora-is-near/aurora-engine/issues/191#issuecomment-886572448
- [x] fn `ft_balance_of` returns number instead of `String` number. See: https://github.com/aurora-is-near/aurora-engine/issues/191#issuecomment-886572448
- [x] fn `ft_metadata` does not exist

Related issues:
* ~~https://github.com/aurora-is-near/aurora-engine/issues/188~~
* ~~https://github.com/aurora-is-near/aurora-engine/issues/177~~
* ~~https://github.com/aurora-is-near/aurora-engine/issues/176~~

Related PRs:
* https://github.com/aurora-is-near/aurora-engine/pull/183

[NEP-141]: https://github.com/near/NEPs/blob/master/specs/Standards/FungibleToken/Core.md

**Comment by mfornet** [comment]
Regarding NEP-141 compliance here are some incompatibilities that should be addressed. Notice this is not a comprehensive list of all issues with our implementation, for that we need to go through every I/O interface defined by NEP-141 and check the implementation is correct.

- [ ] `storage_deposit` doesn't return valid json. For example: `near call aurora storage_deposit '{}' --accountId=bear.near` returns `'{"total": "0", "available": "0",}'` (last comma is not valid)
- [ ] `ft_balance_of` returns number instead of string. For example: `near view aurora ft_balance_of '{"account_id": "bear.near"}'` returns `100000000000000000` instead of `"100000000000000000"`
- [ ] `ft_metadata` is not available.
