### ISSUE TITLE
Engine method `call` has no way to attach ETH

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora-engine#309]
The [method `call`](https://github.com/aurora-is-near/aurora-engine/blob/f1ebb8264383e7047661f830f75849f872df47e6/engine/src/lib.rs#L194) is supposed to be equivalent to the [method `submit`](https://github.com/aurora-is-near/aurora-engine/blob/f1ebb8264383e7047661f830f75849f872df47e6/engine/src/lib.rs#L206), except allows interacting with the EVM from a NEAR account as opposed to an Aurora account. However `call` does not have any way to attach an ETH balance to the transaction which greatly limits its usefulness.

I propose we add a `value` field to [`FunctionCallArgs` struct](https://github.com/aurora-is-near/aurora-engine/blob/f1ebb8264383e7047661f830f75849f872df47e6/engine/src/parameters.rs#L113) to address this issue.

Note: to preserve backwards compatibility we may wish to accept both a version of `FunctionCallArgs` with and without the new field; in the case it is not given it defaults to 0 (the current behaviour). This may or may not be possible since borsh is not a self-describing format. If there are currently no mainnet usages of `call` then maybe the breaking change is fine.

**Comment by mfornet** [comment]
We can have a custom borsh deserialiser that reads the first two fields, and if there is some extra data in the end it reads it as the value (attached eth), this way we preserve backwards compatibility.

**Comment by andrcmdr** [comment]
Finally find a way to overcome orphaning rules difficulties and made a [PR](https://github.com/aurora-is-near/aurora-engine/pull/338).

Here's the feature branches:

[https://github.com/aurora-is-near/aurora-engine/commits/value-field-for-call-args](https://github.com/aurora-is-near/aurora-engine/commits/value-field-for-call-args)

[https://github.com/aurora-is-near/aurora-engine/commits/value-field-for-call-args](https://github.com/aurora-is-near/aurora-engine/tree/toolchain-and-workspace-update)

Hope everything will work fine in current CI configuration ('cause not sure about this, due to toolkit update).

This is my first PR, I was doing my best, so don't hit me hard. =) Anyway, I rely on your advises and support guys!

**Comment by andrcmdr** [comment]
I was radically change and simplify logic (following KISS & DRY), using more straightforward and explicit way with relying on generic borsh deserialization (`io.read_input_borsh()` and current `to_value()` method). (Thanks to @birchmd for working on loose coupling decomposition of SDK methods and host functions to IO trait for standalone engine).

Seems like now it works more reliable, rather than when using `impl Trait` based type matching implementation, which was less obvious, more implicit, less readable.
