### ISSUE TITLE
Understand scope of calls executed by admin

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-engine#411]
We are considering the possibility of signing txs on behalf of the relayer directly with `aurora` account. Main benefit is that the tx is initiated and the result is executed in a single block. This will help indexer (https://github.com/aurora-is-near/aurora.js/pull/26#pullrequestreview-847852598) and probably it will lower the cost of each tx.

For security reasons we can create a Function Call Key, that only can execute `submit` method. However, there are some assumptions made in the engine when the account executing the tx is `aurora`, that it is treated specially, like an admin account. This key will be stored most likely in a hot wallet (on file system) so it is important it can't compromise anything.

This issue is about understanding if calling `submit` method from `aurora` account is feasible, all places where it is treated like an admin, and wether something should be changed in order for make this happen.

**Comment by birchmd** [comment]
I do not see any security problems.

By making `aurora` call itself directly instead of `relay.aurora`, we change the `predecessor_account_id` of transactions hitting the `submit` method. As far as I can tell the only thing the `predecessor_account_id` is used for is knowing where to pay the ETH gas fee to. Whether this goes to the address for `relay.aurora` or `aurora` is of no concern to us because we control it either way.

As @mfornet has pointed out before, there would be a security concern if it were possible for a user to make other calls from inside `submit` (eg via a precompile that makes NEAR calls) because there are other functions (especially related to the ETH and ERC-20 connectors) which do care about whether the `predecessor_account_id` is `aurora`. As of today EVM execution is entirely sandboxed from the rest of NEAR (apart from the carefully controlled exit precompiles that do not make use of the `predecessor_account_id`), so this is not a problem.
