### ISSUE TITLE
Contract deploy error

### ISSUE THREAD

**Issue by Danutu89** [aurora-is-near/aurora-engine#419]
I encounter this error on mainnet while trying to deploy a contract
but on testnet it worked
any ideas what might be ?

![image](https://user-images.githubusercontent.com/50809070/150180979-2477afc1-63c9-473a-bf10-b334da294979.png)

**Comment by birchmd** [comment]
Hi @Danutu89 thanks for your report.

The screenshot there is not very useful. It would be better to link to the explorer instead of giving a screenshot. I assume you are talking about [this transaction](https://explorer.mainnet.aurora.dev/tx/0x2753b7134580639b9aa51cd7c39e6cfb7565c77bc4496383914153809c6d6e50/internal-transactions).

Unfortunately, our Aurora explorer does not display errors properly. However, you can connect the Aurora transaction to the one on NEAR using the block height of the transaction. In your case that height is 57709877, which we can look up on the NEAR explorer to be [this block](https://explorer.mainnet.near.org/blocks/Gvqd6ebZhJdxcTAWvauTDwhgGURQURtSPf158v6YqJhK), which contains [this transaction](https://explorer.mainnet.near.org/transactions/6mnxwtF45MngK4WqhNyCxeFYRMtiu1B35thJ7B2EuA9A) (among others). You can see in the logs `signer_address 0x7519af26f1cb97141ef7cfb339e3550298dbea33`, so you know that one is yours.

The NEAR transaction shows the output result in hex, which still is not very helpful if you do not know what it means. But I can tell you it corresponds to the error `OutOfFund`, which is raised when you do not have sufficient ETH for the transaction.

And indeed, looking at your transaction in the Aurora explorer we see you set a gas limit of 4.5 million, and a gas price of 10 GWei, meaning you would need 0.045 ETH to execute the transaction, but your account only has 0.016 ETH. Therefore the transaction fails.

If you want your transaction to succeed, try setting a lower gas price or bridging more ETH to your account.

Returning clearer error messages to our users is something we want to improve. Thanks for reporting this as a reminder of how painful it is to see what the error on a transaction was; we will do better in the future.

**Comment by Danutu89** [comment]
Hi @birchmd 

i ve tried with more eth and this is the result 


https://explorer.mainnet.aurora.dev/tx/0xd84ec60b91262d03d9d78dc5ad654741a86613906ba77c630a63dd998bcb145f/internal-transactions


![MicrosoftTeams-image](https://user-images.githubusercontent.com/50809070/150789275-94084609-2b34-4572-a642-10e14ab898bc.png)

**Comment by birchmd** [comment]
It's the same error @Danutu89 

In the transaction you set the gas limit as 4.5 million, and a gas price of 10 GWei, meaning you would need 0.045 ETH to execute the transaction. Your account has 0.02 ETH, which is not enough. You can see your ETH balance on the explorer: https://explorer.mainnet.aurora.dev/address/0x7519AF26f1Cb97141Ef7CfB339E3550298dbEA33/transactions

You can also sent the gas price of your transaction lower instead of adding more ETH to your account.

**Comment by birchmd** [comment]
@Danutu89 

It looks like your contract deployment did succeed in [this transaction](https://explorer.mainnet.aurora.dev/tx/0x503c7775a2f9e2f0690a254f2f7f147ad034168a058ec8a5a1fc4a5687c5c2f9/internal-transactions). And your first interaction with that contract also succeeded in [this transaction](https://explorer.mainnet.aurora.dev/tx/0x524a5b6255008c7ea114ad4aa56e7282f61643fd4050fc45b0378a8f5f307125/internal-transactions). The failed transaction you linked is another interaction with the same contract, sending the same data. Looking at the prior successful transaction, we can see it only consumed 46k gas, 1% of the 4.5 million gas limit. You should set the gas limit of your contract interaction transactions lower (say 50k) so that you do not have to have such a high ETH balance to execute them.
