### ISSUE TITLE
EvmErc20.bin: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-engine#465]
When pulling aurora-engine as a library dependency compilation fails since it tries to load a file during compilation that doesn't exist: `EvmErc20.bin`

```
error: couldn't read /Users/marcelo/.cargo/git/checkouts/aurora-engine-7e378a275ccc464a/0c8db05/engine/src/../../etc/eth-contracts/res/EvmErc20.bin: No such file or directory (os error 2)
    --> /Users/marcelo/.cargo/git/checkouts/aurora-engine-7e378a275ccc464a/0c8db05/engine/src/engine.rs:1081:26
     |
1081 |     let erc20_contract = include_bytes!("../../etc/eth-contracts/res/EvmErc20.bin");
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is there anyway to explicitly add this file to the package that cargo downloads while pulling engine as a dependency?

As a short term solution I manually created this file (empty) to unblock me.

**Comment by joshuajbouw** [comment]
You must compile it first.

`make etc/eth-contracts/res/EvmErc20.bin` should do it.

**Comment by mfornet** [comment]
Notice that I'm using the engine as a library, not as a binary.

**Comment by joshuajbouw** [comment]
Right, there are ways to improve this that can be looked into so that isn't particularly required when using it as a library. Which sub-libraries are you using explicitly?

**Comment by birchmd** [comment]
My work-around for this has been to make the Engine a git submodule of my project and then I can build the ERC-20 contract for the Engine as part of the build. For example: https://github.com/birchmd/aurora-cli-rs

Though, I agree with @joshuajbouw that probably the right fix for this is to have everything that does not require the ERC-20 contract in a separate crate from what does require it. Then you only need to worry about the ERC-20 contract if you are actually using code that requires it.

**Comment by joshuajbouw** [comment]
^ Thats what I had done. Included it as a git submodule. The engine itself should be strictly a compiled binary. Then it pulls in everything else from libraries. That would fix a number of these issues as well.

**Comment by mfornet** [comment]
> Which sub-libraries are you using explicitly?

@joshuajbouw I'm only using [aurora_engine::parameters](https://github.com/aurora-is-near/borealis-refiner/blob/5761e9b6260061278cc62b7aedcbde9a6154dbcd/refiner-lib/src/refiner.rs#L7)

**Comment by birchmd** [comment]
Another idea here: we could commit `EvmErc20.bin` to the engine repo so that it is always present. The drawback of this approach is the possibility of it being out of sync with the corresponding solidity source code, but that could be mitigated with an additional CI check perhaps. I am generally opposed to committing generated files to repositories, but in this case it might make sense.

The reason I am revisiting the submodule work around is because the engine becomes like a virus that infects libraries. If library X depends on `aurora-engine` (and accomplishes this by having the engine as a submodule), and library Y depends on X, then Y needs to have X as a submodule to compile it otherwise Y experiences the same error while trying to compile X's engine dependency. Having an increasingly deep chain of submodules as more libraries are added to the dependency chain does not feel great, which is why I am proposing another solution.

**Comment by Aurora-ClickUp** [comment]
I'm quite against commiting pre-compiled code. However, we should refactor the lib so that we treat it more like a binary, less like a library.
