### ISSUE TITLE
Some `eth_call` requests have empty response without explicit error

### ISSUE THREAD

**Issue by HarmlessEvil** [aurora-is-near/aurora-engine#592]
Hello! We deployed a smart contract with some `view` methods that return `uint256`. However, when we query them on some blocks we receive empty response without an explicit error. From my point of view, it's a violation of the ABI, because Solidity doesn't have `null` values at all.

Here are some examples:
```shell
curl -s https://testnet.aurora.dev/ -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0","id":2,"method":"eth_call","params":[{"data":"0xa035b1fe","from":"0x0000000000000000000000000000000000000000","to":"0xd4fca6402aef86762f4263603a0d7a3cf45d4754"},"0x5de1d38"]}
' | jq
```

We call method `Price() view uint256`, which should return the value. However, we get this as the response:
```json
{
  "jsonrpc": "2.0",
  "id": 2,
  "result": "0x"
}
```

Take a look at the `result` field. On the next block the response behaves as expected.

We also have a request that returns "null" on every block in the sane range (after contract creation, before current head):
```shell
curl -s https://testnet.aurora.dev/ -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0","id":48,"method":"eth_call","params":[{"data":"0xc8318c100000000000000000000000000000000000000000000000000000000000000000","from":"0x0000000000000000000000000000000000000000","to":"0xd4fca6402aef86762f4263603a0d7a3cf45d4754"},98442551]}   
' | jq
```

**Comment by birchmd** [comment]
Thanks for the report @HarmlessEvil 

I am closing this because it is not an issue with the engine, but rather with the backend which is serving the testnet RPC. The mainnet RPC does not have this issue (it would correctly return an error response). We are currently in the process of switching over the testnet RPC backend, so this issue should be resolved for you soon.

In the meantime, I can tell you that the call to `0xd4fca6402aef86762f4263603a0d7a3cf45d4754` is failing with an explicit `revert`, but there is no additional information (ie no revert message).
